name: Stable DNAJT build
on:
  push:

jobs:
  build:
    name: Build and upload DNAJT
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'macos-13'
            version: '15.2'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: brew install ldid

      - name: Change version to tag
        run: sed -e '/MARKETING_VERSION = .*/s/= .*/= ${{ github.ref_name }}/' -i '' Build.xcconfig

      - name: Get version
        id: version
        run: echo "version=$(grep MARKETING_VERSION Build.xcconfig | sed -e "s/MARKETING_VERSION = //g")" >> $GITHUB_OUTPUT

      - name: Echo version
        run: echo "${{ steps.version.outputs.version }}"

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: ${{ matrix.version }}

      - name: Build DNAJT
        run: make build | xcpretty && exit ${PIPESTATUS[0]}

      - name: Fakesign app
        run: make fakesign

      - name: Convert to IPA
        run: make ipa

      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%c')" >> $GITHUB_OUTPUT

      - name: Add version to IPA file name
        run: mv DNAJT.ipa DNAJT-${{ steps.version.outputs.version }}.ipa

      - name: Upload DNAJT.ipa Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: DNAJT-${{ steps.version.outputs.version }}.ipa
          path: DNAJT-${{ steps.version.outputs.version }}.ipa
